name: python-academy-friday
dependencies:
  - python>=3.9
  - pandas
  - jupyterlab
  - scikit-learn
  - matplotlib
  - seaborn
  - openpyxl
  - ipywidgets
  - conda-forge::typeguard
  - conda-forge::prophet